
const NONALCOHOLIC = {
	Allspice: 1,
	"Angostura Bitters": 1,
	Bitters: 2,
	"Brown sugar": 1,
	"Carbonated water": 1,
	Cinnamon: 2,
	"Coca-Cola": 2,
	Cherry: 1,
	Cloves: 1,
	Coffee: 2,
	"Corn syrup": 1,
	"Cranberry juice": 1,
	Cream: 2,
	"Creme de Banane": 2,
	"Creme de Cassis": 2,
	"Creme de Mure": 2,
	"Club soda": 1,
	"Creme de Cacao": 2,
	"Cherry Juice": 1,
	"demerara Sugar": 1,
	Egg: 1,
	"Egg White": 2,
	"Egg yolk": 2,
	Espresso: 2,
	Fanta: 2,
	"Fruit punch": 3,
	"Ginger ale": 2,
	Ginger: 1,
	"Grapefruit juice": 1,
	"Grape Soda": 2,
	"Heavy cream": 2,
	"Hot Chocolate": 2,
	Ice: 0,
	Kiwi: 1,
	Lemon: 1,
	lemon: 1,
	"Lemon Juice": 1,
	"lemon juice": 1,
	"Lemon juice": 1,
	"Lemon peel": 2,
	Lemonade: 2,
	"Light cream": 2,
	"Lime juice": 1,
	"Lime Juice": 1,
	Lime: 1,
	Mango: 2,
	Milk: 2,
	Mint: 2,
	"Mountain Dew": 2,
	Nutmeg: 2,
	"Orange juice": 1,
	"Orange bitters": 1,
	"Orange Bitters": 1,
	"Orange Peel": 0,
	"Passion fruit juice": 1,
	"Peach nectar": 2,
	"Peppermint extract": 2,
	"Pineapple juice": 1,
	"Pink lemonade": 2,
	"Powdered sugar": 0,
	"Red Chili Flakes": 1,
	"Soda water": 1,
	Sugar: 1,
	"Sugar syrup": 1,
	"Sugar Syrup": 1,
	Sprite: 2,
	Surge: 2,
	"Tomato juice": 1,
	Vanilla: 1,
	"Vanilla extract": 1,
	Water: 1,
	Wormwood: 2,
};

export default NONALCOHOLIC;