export const INGREDIENTS = {
	"absolut vodka": { isAlcoholic: true, price: 6 },
	"absolut citron": { isAlcoholic: true, price: 6 },
	"absolut kurant": { isAlcoholic: true, price: 6 },
	advocaat: { isAlcoholic: true, price: 5 },
	allspice: { isAlcoholic: false, price: 1 },
	"almond flavoring": { isAlcoholic: false, price: 1 },
	applejack: { isAlcoholic: true, price: 7 },
	"apple brandy": { isAlcoholic: true, price: 6 },
	"apple juice": { isAlcoholic: false, price: 1 },
	"apricot nectar": { isAlcoholic: false, price: 1 },
	absinthe: { isAlcoholic: true, price: 4 },
	amaretto: { isAlcoholic: true, price: 5 },
	"angostura bitters": { isAlcoholic: false, price: 1 },
	"añejo rum": { isAlcoholic: true, price: 5 },
	"apricot brandy": { isAlcoholic: true, price: 4 },
	"baileys irish cream": { isAlcoholic: true, price: 5 },
	"bacardi limon": { isAlcoholic: true, price: 4 },
	banana: { isAlcoholic: false, price: 1 },
	"banana liqueur": { isAlcoholic: true, price: 6 },
	beer: { isAlcoholic: true, price: 3 },
	benedictine: { isAlcoholic: true, price: 5 },
	brandy: { isAlcoholic: true, price: 6 },
	bitters: { isAlcoholic: false, price: 2 },
	"black sambuca": { isAlcoholic: true, price: 6 },
	"blackstrap rum": { isAlcoholic: true, price: 7 },
	"blended whiskey": { isAlcoholic: true, price: 5 },
	"blended scotch": { isAlcoholic: true, price: 5 },
	"blue curacao": { isAlcoholic: true, price: 3 },
	"blackberry brandy": { isAlcoholic: true, price: 4 },
	"blackcurrant cordial": { isAlcoholic: false, price: 3 },
	bourbon: { isAlcoholic: true, price: 4 },
	"brown sugar": { isAlcoholic: false, price: 1 },
	campari: { isAlcoholic: true, price: 3 },
	"carbonated water": { isAlcoholic: false, price: 1 },
	"caramel coloring": { isAlcoholic: false, price: 1 },
	"chocolate syrup": { isAlcoholic: false, price: 1 },
	"cherry juice": { isAlcoholic: false, price: 1 },
	chocolate: { isAlcoholic: false, price: 2 },
	"chocolate liqueur": { isAlcoholic: true, price: 6 },
	"chambord raspberry liqueur": { isAlcoholic: true, price: 5 },
	cider: { isAlcoholic: true, price: 4 },
	cinnamon: { isAlcoholic: false, price: 2 },
	cloves: { isAlcoholic: false, price: 1 },
	"coca-cola": { isAlcoholic: false, price: 2 },
	cointreau: { isAlcoholic: true, price: 6 },
	cachaca: { isAlcoholic: true, price: 4 },
	cherry: { isAlcoholic: false, price: 1 },
	"cherry brandy": { isAlcoholic: true, price: 3 },
	"cherry heering": { isAlcoholic: true, price: 3 },
	"champagne flute": { isAlcoholic: false, price: 0 },
	champagne: { isAlcoholic: true, price: 5 },
	coffee: { isAlcoholic: false, price: 2 },
	"coffee liqueur": { isAlcoholic: true, price: 4 },
	"coffee brandy": { isAlcoholic: true, price: 5 },
	cognac: { isAlcoholic: true, price: 7 },
	"condensed milk": { isAlcoholic: false, price: 1 },
	corona: { isAlcoholic: true, price: 3 },
	"corn syrup": { isAlcoholic: false, price: 1 },
	"cranberry juice": { isAlcoholic: false, price: 1 },
	"cranberry vodka": { isAlcoholic: true, price: 4 },
	cream: { isAlcoholic: false, price: 2 },
	"creme de banane": { isAlcoholic: false, price: 2 },
	"creme de cassis": { isAlcoholic: false, price: 2 },
	"creme de mure": { isAlcoholic: false, price: 2 },
	"club soda": { isAlcoholic: false, price: 1 },
	"creme de cacao": { isAlcoholic: false, price: 2 },
	"coconut liqueur": { isAlcoholic: true, price: 5 },
	"crown royal": { isAlcoholic: true, price: 6 },
	"dark rum": { isAlcoholic: true, price: 4 },
	"demerara sugar": { isAlcoholic: false, price: 1 },
	"dry vermouth": { isAlcoholic: true, price: 5 },
	"dubonnet rouge": { isAlcoholic: true, price: 6 },
	"elderflower cordial": { isAlcoholic: false, price: 3 },
	egg: { isAlcoholic: false, price: 1 },
	"egg white": { isAlcoholic: false, price: 2 },
	"egg yolk": { isAlcoholic: false, price: 2 },
	everclear: { isAlcoholic: true, price: 4 },
	espresso: { isAlcoholic: false, price: 2 },
	fanta: { isAlcoholic: false, price: 2 },
	frangelico: { isAlcoholic: true, price: 4 },
	falernum: { isAlcoholic: false, price: 3 },
	figs: { isAlcoholic: false, price: 1 },
	fruit: { isAlcoholic: false, price: 1 },
	"fruit juice": { isAlcoholic: false, price: 1 },
	"fruit punch": { isAlcoholic: false, price: 3 },
	firewater: { isAlcoholic: false, price: 2 },
	galliano: { isAlcoholic: true, price: 6 },
	gin: { isAlcoholic: true, price: 3 },
	"green creme de menthe": { isAlcoholic: false, price: 3 },
	ginger: { isAlcoholic: false, price: 1 },
	"ginger ale": { isAlcoholic: false, price: 2 },
	"ginger beer": { isAlcoholic: false, price: 2 },
	goldschlager: { isAlcoholic: true, price: 6 },
	"grand marnier": { isAlcoholic: true, price: 5 },
	"grapefruit juice": { isAlcoholic: false, price: 1 },
	"grain alcohol": { isAlcoholic: true, price: 4 },
	"grape soda": { isAlcoholic: false, price: 2 },
	grenadine: { isAlcoholic: true, price: 5 },
	"green chartreuse": { isAlcoholic: true, price: 4 },
	"godiva liqueur": { isAlcoholic: true, price: 6 },
	"heavy cream": { isAlcoholic: false, price: 2 },
	honey: { isAlcoholic: false, price: 1 },
	"hot chocolate": { isAlcoholic: false, price: 2 },
	"hot damn": { isAlcoholic: false, price: 4 },
	"hot sauce": { isAlcoholic: false, price: 1 },
	"irish cream": { isAlcoholic: true, price: 5 },
	"irish whiskey": { isAlcoholic: true, price: 6 },
	jägermeister: { isAlcoholic: true, price: 6 },
	"jack daniels": { isAlcoholic: true, price: 7 },
	"jim beam": { isAlcoholic: true, price: 6 },
	ice: { isAlcoholic: false, price: 0 },
	kahlua: { isAlcoholic: true, price: 5 },
	"kiwi liqueur": { isAlcoholic: true, price: 4 },
	kiwi: { isAlcoholic: false, price: 1 },
	"kool-aid": { isAlcoholic: true, price: 6 },
	lager: { isAlcoholic: true, price: 7 },
	lavender: { isAlcoholic: false, price: 1 },
	lemon: { isAlcoholic: false, price: 1 },
	"lemon juice": { isAlcoholic: false, price: 1 },
	"lemon peel": { isAlcoholic: false, price: 1 },
	lemonade: { isAlcoholic: false, price: 2 },
	"lillet blanc": { isAlcoholic: true, price: 4 },
	"light cream": { isAlcoholic: false, price: 2 },
	"light rum": { isAlcoholic: true, price: 4 },
	"lime juice": { isAlcoholic: false, price: 1 },
	lime: { isAlcoholic: false, price: 1 },
	milk: { isAlcoholic: false, price: 2 },
	"malibu rum": { isAlcoholic: true, price: 6 },
	mango: { isAlcoholic: false, price: 2 },
	"maraschino cherry": { isAlcoholic: true, price: 5 },
	mezcal: { isAlcoholic: true, price: 4 },
	mint: { isAlcoholic: false, price: 2 },
	"maraschino liqueur": { alcoholic: true, price: 5 },
	"midori melon liqueur": { isAlcoholic: true, price: 6 },
	"mountain dew": { isAlcoholic: false, price: 2 },
	nutmeg: { isAlcoholic: false, price: 2 },
	olive: { isAlcoholic: false, price: 1 },
	"olive brine": { isAlcoholic: false, price: 2 },
	orange: { isAlcoholic: false, price: 1 },
	"orange juice": { isAlcoholic: false, price: 1 },
	"orange bitters": { isAlcoholic: false, price: 1 },
	"orange peel": { isAlcoholic: false, price: 0 },
	pepper: { isAlcoholic: false, price: 1 },
	"peppermint extract": { isAlcoholic: false, price: 2 },
	port: { isAlcoholic: true, price: 6 },
	"peach bitters": { isAlcoholic: false, price: 1 },
	"peach nectar": { isAlcoholic: false, price: 2 },
	"peach schnapps": { isAlcoholic: true, price: 3 },
	"peach vodka": { isAlcoholic: true, price: 6 },
	"peachtree schnapps": { isAlcoholic: true, price: 3 },
	"pisang ambon": { isAlcoholic: true, price: 5 },
	"pineapple juice": { isAlcoholic: false, price: 1 },
	"pineapple syrup": { isAlcoholic: false, price: 1 },
	"pink lemonade": { isAlcoholic: false, price: 2 },
	pisco: { isAlcoholic: true, price: 6 },
	"passion fruit juice": { isAlcoholic: false, price: 1 },
	"pomegranate juice": { isAlcoholic: false, price: 1 },
	"powdered sugar": { isAlcoholic: false, price: 0 },
	prosecco: { isAlcoholic: true, price: 4 },
	"raspberry vodka": { isAlcoholic: true, price: 5 },
	"red chili flakes": { isAlcoholic: false, price: 1 },
	"red wine": { isAlcoholic: true, price: 5 },
	ricard: { isAlcoholic: true, price: 5 },
	rose: { isAlcoholic: true, price: 4 },
	rum: { isAlcoholic: true, price: 5 },
	"rye whiskey": { isAlcoholic: true, price: 5 },
	salt: { isAlcoholic: false, price: 0 },
	sambuca: { isAlcoholic: true, price: 5 },
	sherry: { isAlcoholic: true, price: 4 },
	"soy sauce": { isAlcoholic: false, price: 1 },
	"soda water": { isAlcoholic: false, price: 1 },
	"spiced rum": { isAlcoholic: true, price: 6 },
	"strawberry schnapps": { isAlcoholic: true, price: 4 },
	strawberries: { isAlcoholic: false, price: 1 },
	sugar: { isAlcoholic: false, price: 1 },
	"sugar syrup": { isAlcoholic: false, price: 1 },
	scotch: { isAlcoholic: true, price: 5 },
	"sloe gin": { isAlcoholic: true, price: 4 },
	"sour mix": { isAlcoholic: false, price: 1 },
	"southern comfort": { isAlcoholic: true, price: 4 },
	sprite: { isAlcoholic: false, price: 2 },
	surge: { isAlcoholic: false, price: 2 },
	"st. germain": { isAlcoholic: true, price: 6 },
	"sweet and sour": { isAlcoholic: false, price: 1 },
	"sweet vermouth": { isAlcoholic: true, price: 6 },
	"triple sec": { isAlcoholic: true, price: 7 },
	"tomato juice": { isAlcoholic: false, price: 1 },
	"tonic water": { isAlcoholic: false, price: 2 },
	"tennessee whiskey": { isAlcoholic: true, price: 6 },
	tequila: { isAlcoholic: true, price: 5 },
	thyme: { isAlcoholic: false, price: 1 },
	vodka: { isAlcoholic: true, price: 5 },
	vanilla: { isAlcoholic: false, price: 1 },
	"vanilla extract": { isAlcoholic: false, price: 1 },
	"vanilla ice-cream": { isAlcoholic: false, price: 2 },
	"vanilla syrup": { isAlcoholic: false, price: 1 },
	"vanilla vodka": { isAlcoholic: true, price: 5 },
	vermouth: { isAlcoholic: true, price: 6 },
	water: { isAlcoholic: false, price: 1 },
	wormwood: { isAlcoholic: false, price: 2 },
	"worcestershire sauce": { isAlcoholic: true, price: 6 },
	"wild turkey": { isAlcoholic: true, price: 4 },
	"151 proof rum": { isAlcoholic: true, price: 5 },
	wine: { isAlcoholic: true, price: 6 },
	"whipped cream": { isAlcoholic: false, price: 1 },
	"whipping cream": { isAlcoholic: false, price: 1 },
	whiskey: { isAlcoholic: true, price: 6 },
	whisky: { isAlcoholic: true, price: 6 },
	"white rum": { isAlcoholic: true, price: 5 },
	"white wine": { isAlcoholic: true, price: 4 },
	yoghurt: { isAlcoholic: false, price: 1 },
	"yukon jack": { isAlcoholic: true, price: 7 },
	zima: { isAlcoholic: true, price: 7 },
};

export default INGREDIENTS;